---
- hosts: 172.31.11.67
  become: yes
  tasks:  
  - include_tasks: myfile.yml
  - name: i want to install webserver
    apt:
      name: apache2

  - name: copy index file into node side
    copy:
      src: myindexfile
      dest: /var/wwww/html/index.html
