---
- hosts: 172.31.11.67
  become: yes
  tasks:  
  - include_tasks: myfile.yml
  - name: i want to install webserver
    apt:
      name: apache2

  - name: copy index file into node side
    copy:
      src: myindexfile
      dest: /var/www/html/index.html

  - name: i want to download internet filess
    get_url:
         url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
         dest: /home/ubuntu/apache-tomcat-10.0.20.tar.gz
         force_basic_auth: yes
  - name: i want to copy dynamic file into nodes
    template:  
      src: myindex.j2
      dest: /var/www/html/index.html
    notify: restartwebserver
    handlers:
  - name: restartwebserver
    service: 
        name: apache2
        state: restarted    

